### ISSUE TITLE
Can you upload the template data?

### ISSUE THREAD

**Issue by NonvolatileMemory** [hyx1999/SAM-Decoding#1]
Thanks for your great work!

I run the prepare_prompts.py, but it shows ```Can't read sam_data/templates/vicuna.json```.

Can you kindly upload the template data? Or maybe your sam?

**Comment by hyx1999** [comment]
Sorry, I forgot to upload the template. The template that vicuna uses is as follows:
vicuna.json:
{
    "description": "Template used by Vicuna.",
    "prompt_input": "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.\n\nUSER: {instruction}\n\n{input}\n\nASSISTANT:",
    "prompt_no_input": "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.\n\nUSER: {instruction}\n\nASSISTANT:"
}

Later, we will upload the data to Google Cloud Drive.

**Comment by hyx1999** [comment]
The data we used is available at the following link: 
https://drive.google.com/file/d/1N7FARwsGQXIbL_3B2uEYh3CkDh4Bc6it/view?usp=share_link

**Comment by NonvolatileMemory** [comment]
Thanks for your reply, another question is 

```Traceback (most recent call last):
  File "/home/aiops/ducx/SAM-Decoding/tools/gen_sam_alpaca_sam_only.py", line 48, in <module>
    sam = build_sam(samd_config, batch_tokens, tokenizer.eos_token_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: build_sam() takes 2 positional arguments but 3 were given
```

After I read the code of sam_static.py, I think we only need the ```batch_tokens, tokenizer.eos_token_id```, but idk do we really need samd_config here?

**Comment by hyx1999** [comment]
Yes, we don't need samd_config. Thank you very much for pointing out the bug 🫶, I have fixed it.

**Comment by NonvolatileMemory** [comment]
thanks~
